query GetProducts {
  products {
    totalItems
    items {
      id
      name
      slug
      description
      featuredAsset {
        id
        preview
      }

      variants {
        id
        priceWithTax
        currencyCode
      }
    }
  }
}
